name: cloc
on:
  pull_request:

# Cancel the workflow in progress in newer build is about to start.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  TARGET: "tinygrad"
  EXT: "py"

jobs:
  cloc:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: pr
      - name: Checkout base code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          path: base
      - name: Count Lines Of Code
        id: loc
        run: |
          curl -sLO https://github.com/AlDanial/cloc/releases/download/v1.96/cloc-1.96.tar.gz && \
          tar xf cloc-1.96.tar.gz && mv cloc-1.96/cloc .

          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "loc_content<<$EOF" >> "$GITHUB_ENV"
          echo "LOC|files|blank|comment|code" >> "$GITHUB_ENV"
          echo ":---|---:|---:|---:|---:" >> "$GITHUB_ENV"
          ./cloc --include-ext="$EXT" --diff "base/$TARGET" "pr/$TARGET" | \
            grep "SUM" -A4 | sed '1d;s/^\s*//g' | tr -s ' ' | tr ' ' '|' >> "$GITHUB_ENV"
          echo "$EOF" >> "$GITHUB_ENV"

      - name: Comment Code Lines
        continue-on-error: true
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          recreate: true
          header: LOC
          message: |
            ### Lines Of Code

            ${{ env.loc_content }}

